version: '3'

services:
  frontend:
    build: ./frontend
    container_name: behethKade_frontend
    ports:
      - "3000:3000"
    depends_on:
      - apigateway
    networks:
      - bk  
      
  apigateway:
    build: ./backend/apigateway
    container_name: behethKade_APIGateway
    ports:
      - "8000:8000"
    environment:
      REACT_APP_GATEWAY_PORT: 8000
      REACT_APP_ITEM_SERVICES_URI: http://behethKade_ItemService:4000
      REACT_APP_ORDER_SERVICES_URI: http://behethKade_OrderService:5000
      REACT_APP_PAYMENT_SERVICES_URI: http://behethKade_PaymentService:6000
      REACT_APP_USER_SERVICES_URI: http://behethKade_UserService:7000
    depends_on:
      - userservice
      - itemservice
      - orderservice
      - paymentservice
    networks:
      - bk  

  userservice:
    build: ./backend/userservice
    container_name: behethKade_UserService
    ports:
      - "7000:7000"
    networks:
      - bk  

  itemservice:
    build: ./backend/itemservice
    container_name: behethKade_ItemService
    ports:
      - "4000:4000"
    networks:
      - bk  

  orderservice:
    build: ./backend/orderservice
    container_name: behethKade_OrderService
    ports:
      - "5000:5000"
    networks:
      - bk  

  paymentservice:
    build: ./backend/paymentservice
    container_name: behethKade_PaymentService
    ports:
      - "6000:6000"
    networks:
      - bk  

networks:
  bk:
    driver: bridge
    
# run below command in terminal
# docker compose up -d 
# docker build -t herbal-medicine-selling-platform-frontend .     